import { Inter, Tajawal } from 'next/font/google'
import "@/app/globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import IntlProvider from "@/components/layout/IntlProvider";
import { getMessages } from "next-intl/server";
import { locales } from "@/navigation";
import { Suspense } from 'react'
import { getThemeSettings } from '@/lib/data'

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' })
const tajawal = Tajawal({
  subsets: ['arabic'],
  variable: '--font-tajawal',
  weight: ['400', '700'],
})

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  const dir = locale === 'ar' ? 'rtl' : 'ltr'
  const messages = (await import(`@/locales/${locale}.json`)).default;
  const themeSettings = await getThemeSettings(locale)
  const navigation = themeSettings?.navigation || { items: [] }

  const colorStyles = themeSettings
    ? `
    :root {
      --color-primary: ${themeSettings.primaryColor};
      --color-primary-rgb: ${themeSettings.primaryColorRgb};
      --color-primary-tint: ${themeSettings.primaryColorTint};
      --color-secondary: ${themeSettings.secondaryColor};
      --color-dark: ${themeSettings.darkColor};
      --color-light-bg: ${themeSettings.lightBgColor};
      --color-footer-bg: ${themeSettings.footerBackgroundColor};
    }
  `
    : ''

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <head>
        <style>{colorStyles}</style>
      </head>
      <body className={`${inter.variable} ${tajawal.variable} font-sans`}>
        <IntlProvider locale={locale} messages={messages}>
          <Suspense fallback={null}>
            <Header navigation={navigation} />
          </Suspense>
          <main>{children}</main>
          <Footer navigation={navigation} />
        </IntlProvider>
      </body>
    </html>
  );
}
